version: '2'
services:
    nginx:
        image: nginx:mainline
        volumes:
            - ".docker/nginx.template:/etc/nginx/conf.d/wordpress.template:ro"
            - "./certs/server.crt:/etc/ssl/localhost.crt:ro"
            - "./certs/server.key:/etc/ssl/localhost.key:ro"
        volumes_from:
            - php
        links:
            - php
        ports:
            - "8000:80"
        command: /bin/bash -c "envsubst '$$NGINX_PORT' < /etc/nginx/conf.d/wordpress.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        environment:
            NGINX_PORT: 80
        restart: always

    php:
        image: joshbetz/wordpress
        links:
            - mysql
            - memcached
            - "graphite-statsd:statsd"
        volumes:
            - "./wp-config:/var/www/html/wp-config:ro"
            - "./wp-content/mu-plugins:/var/www/html/wp-content/mu-plugins:ro"
            - "./wp-content/plugins:/var/www/html/wp-content/plugins:rw"
            - "./wp-content/themes:/var/www/html/wp-content/themes:rw"
            - "./wp-content/uploads:/var/www/html/wp-content/uploads:rw"
            - "./wp-content/sunrise.php:/var/www/html/wp-content/sunrise.php:ro"
            - "./wp-content/object-cache.php:/var/www/html/wp-content/object-cache.php:ro"
        environment:
            WORDPRESS_DB_HOST: mysql:3306
            WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
            WORDPRESS_DB_NAME: wordpress
            WORDPRESS_DB_USER: wordpress
            WP_PRODUCTION: ${WP_PRODUCTION}
        restart: always

    wpcli:
        image: joshbetz/wordpress:cli
        command: /usr/local/bin/wp shell --allow-root
        links:
            - mysql
            - memcached
        volumes_from:
            - php
        environment:
            WORDPRESS_DB_HOST: mysql:3306
            WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
            WORDPRESS_DB_NAME: wordpress
            WORDPRESS_DB_USER: wordpress
            WP_PRODUCTION: ${WP_PRODUCTION}

    memcached:
        image: memcached
        restart: always

    mysql:
        image: mariadb
        volumes:
            - ".data:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: ${DB_PASSWORD}
        restart: always

    smtp:
        image: namshi/smtp
        environment:
            MAILNAME: ${MAILNAME}

    graphite-statsd:
        image: graphiteapp/graphite-statsd
        ports:
            - 8080:80
            - 2003-2004:2003-2004
            - 2023-2024:2023-2024
            - 8125:8125/udp
            - 8126:8126
